version: '3'

services:

  postgres:
    hostname: postgres
    image: postgres:latest
    environment:
       - POSTGRES_USER=${DJANGO_DATABASE_USER}
       - POSTGRES_PASSWORD=${DJANGO_DATABASE_PASSWORD}
       - POSTGRES_DB=${DJANGO_DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    hostname: backend
    volumes:
      - .:/app/
    env_file:
      - .env
  
volumes:
  postgresql_data: